version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
      - proxy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: Password1
      POSTGRES_DB: postgres

  proxy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
