services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: Password1
      POSTGRES_DB: postgres

  proxy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "443:443"
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config:
